name: Test Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Setup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
          script: |
            # 1. Enter the directory if it exists and STOP containers
            if [ -d "/home/ubuntu/api" ]; then
              cd /home/ubuntu/api
              sudo docker compose down || true
            fi

            # 2. Now it is safe to delete and recreate
            sudo rm -rf /home/ubuntu/api
            mkdir -p /home/ubuntu/api
            cd /home/ubuntu/api

            # 3. Fresh Clone
            git clone -b main https://github.com/gmenchaca/git-backend-2.git .
            echo "${{ secrets.DOT_ENV_MAIN }}" > .env

            # 4. Start Containers
            sudo docker compose up -d --build

            # 5. Run PHP commands (Wait 5 seconds to ensure PHP-FPM is ready)
            sleep 5
            sudo docker exec api-app-1 composer install --no-dev --no-interaction --optimize-autoloader
            sudo docker exec -u root api-app-1 chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
            sudo docker exec api-app-1 php artisan optimize:clear
            sudo docker exec api-app-1 php artisan config:cache 